![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

In [10]:
# Import necessary packages
import pandas as pd
import numpy as np

In [11]:
ori_data_price = pd.read_csv('data/airbnb_price.csv')
print(ori_data_price.head())
print('--------------------------------------------------------------------------')
ori_data_room_type = pd.read_excel('data/airbnb_room_type.xlsx')
print(ori_data_room_type.head())
print('--------------------------------------------------------------------------')
ori_data_last_review = pd.read_csv('data/airbnb_last_review.tsv', sep = '\t')
print(ori_data_last_review.head())

   listing_id        price                nbhood_full
0        2595  225 dollars         Manhattan, Midtown
1        3831   89 dollars     Brooklyn, Clinton Hill
2        5099  200 dollars     Manhattan, Murray Hill
3        5178   79 dollars  Manhattan, Hell's Kitchen
4        5238  150 dollars       Manhattan, Chinatown
--------------------------------------------------------------------------
   listing_id                                description        room_type
0        2595                      Skylit Midtown Castle  Entire home/apt
1        3831            Cozy Entire Floor of Brownstone  Entire home/apt
2        5099  Large Cozy 1 BR Apartment In Midtown East  Entire home/apt
3        5178            Large Furnished Room Near B'way     private room
4        5238         Cute & Cozy Lower East Side 1 bdrm  Entire home/apt
--------------------------------------------------------------------------
   listing_id    host_name   last_review
0        2595     Jennifer   May 21 2019
1        3831  LisaRoxanne  July 05 2019
2        5099        Chris  June 22 2019
3        5178     Shunichi  June 24 2019
4        5238          Ben  June 09 2019

In [12]:
# Merge three data tables
Merged_data = pd.merge(ori_data_price, ori_data_room_type, on = 'listing_id')
Merged_data_final = pd.merge(Merged_data, ori_data_last_review, on = 'listing_id')
print(Merged_data_final.head())

   listing_id        price  ...    host_name   last_review
0        2595  225 dollars  ...     Jennifer   May 21 2019
1        3831   89 dollars  ...  LisaRoxanne  July 05 2019
2        5099  200 dollars  ...        Chris  June 22 2019
3        5178   79 dollars  ...     Shunichi  June 24 2019
4        5238  150 dollars  ...          Ben  June 09 2019

[5 rows x 7 columns]

In [13]:
# What are the dates of the earliest and most recent reviews? Store these values as two separate variables with your preferred names.
cp_data = Merged_data_final.copy()
cp_data['last_review'] = pd.to_datetime(cp_data['last_review'])
cp_data = cp_data.sort_values(by = 'last_review')
first_reviewed = cp_data['last_review'].iloc[0].date()
last_reviewed = cp_data['last_review'].iloc[-1].date()
print(f'Earliest: {first_reviewed} \t Recent: {last_reviewed}')

Earliest: 2019-01-01 	 Recent: 2019-07-09

In [14]:
# How many of the listings are private rooms? Save this into any variable.
# print(cp_data['room_type'].unique()) 
# ['PRIVATE ROOM' 'Entire home/apt' 'Private room' 'private room'
#  'ENTIRE HOME/APT' 'entire home/apt' 'SHARED ROOM' 'Shared room'
#  'shared room']
cp_data['room_type'] = cp_data['room_type'].str.lower() # clean data first
nb_private_rooms = cp_data['room_type'].value_counts().get('private room', 0)
print(f'Num of private rooms: {nb_private_rooms}')

Num of private rooms: 11356

In [15]:
# What is the average listing price? Round to the nearest two decimal places and save into a variable.
cp_data['price'] = cp_data['price'].str.replace('dollars', '').str.strip()
cp_data['price'] = cp_data['price'].astype(float)
avg_price = round(cp_data['price'].mean(), 2)
print(f'Average listing price is {avg_price}')

Average listing price is 141.78

In [16]:
# Combine the new variables into one DataFrame called review_dates with four columns in the following order: first_reviewed, last_reviewed, nb_private_rooms, and avg_price. The DataFrame should only contain one row of values.
review_dates = pd.DataFrame({'first_reviewed': [first_reviewed], 'last_reviewed': [last_reviewed], 
              'nb_private_rooms': [nb_private_rooms], 'avg_price': [avg_price]})
print(review_dates)

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78